### ISSUE TITLE
Hardcoded stop-list path

### ISSUE THREAD

**Issue by kirillDanshin** [Obaied/RAKE.Go#1]
Hi.

You send us a pull request here https://github.com/avelino/awesome-go/pull/1229.

I've start my review, but I see that hardcoded stopPath should cause a fail [here](https://github.com/Obaied/RAKE.Go/blob/master/rake.go#L179) should cause a fail [here](https://github.com/Obaied/RAKE.Go/blob/master/rake.go#L34) if file not found, but it should not exist on linux/windows.

**Comment by afjoseph** [comment]
Hi! Thanks for the review.

Yep. That was my bad. Fixed in the latest commit.
